github:
  zip_url: http://example.com/download.zip
  another_url: another value

theme: jekyll-theme-slate
title: Yan | Surface Water Hydrology 
description: Solving water problems in a changing world


